// EVENTLY Mock Data Store (Global Compatibility for file:// and http://)
window.mockData = {
  activeEventId: "evt-01",
  events: [
    {
      id: "evt-01",
      name: "HUGGIE FEST 2026",
      type: "Festival & Boda Privada",
      date: "29 AUG 2026",
      time: "8:00 PM",
      location: "Hacienda San José, Monterrey",
      totalGuests: 450,
      confirmed: 387,
      checkedIn: 241,
      pending: 38,
      declined: 25,
      vendorsCount: 18,
      budgetTotal: 450000,
      budgetSpent: 387000,
      planner: "Sofia Garza",
      status: "ACTIVE",
      coverImage: "assets/images/concert_arena_stage.jpg",
      coverColor: "linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%)",
      badge: "In Progress"
    },
    {
      id: "evt-02",
      name: "Summit Tech Latam 2026",
      type: "Congreso & Conferencia",
      date: "14 OCT 2026",
      time: "9:00 AM",
      location: "Centro de Convenciones Pabellón M",
      totalGuests: 1200,
      confirmed: 940,
      checkedIn: 0,
      pending: 180,
      declined: 80,
      vendorsCount: 24,
      budgetTotal: 850000,
      budgetSpent: 620000,
      planner: "Carlos Mendoza",
      status: "UPCOMING",
      coverImage: "assets/images/corporate_tech_summit.jpg",
      coverColor: "linear-gradient(135deg, #064e3b 0%, #065f46 50%, #047857 100%)",
      badge: "Confirmed"
    },
    {
      id: "evt-03",
      name: "Gala Anual Fundación Arcano",
      type: "Gala Benéfica",
      date: "05 DEC 2026",
      time: "7:30 PM",
      location: "Club Industrial de Monterrey",
      totalGuests: 300,
      confirmed: 265,
      checkedIn: 0,
      pending: 25,
      declined: 10,
      vendorsCount: 12,
      budgetTotal: 320000,
      budgetSpent: 290000,
      planner: "Valeria Rios",
      status: "UPCOMING",
      coverImage: "assets/images/hero_gala_event.jpg",
      coverColor: "linear-gradient(135deg, #701a75 0%, #86198f 50%, #a21caf 100%)",
      badge: "Planning"
    },
    {
      id: "evt-04",
      name: "Lanzamiento CyberShield AI",
      type: "Corporativo & Press",
      date: "12 JUN 2026",
      time: "6:00 PM",
      location: "Torre KOI Sky Lounge",
      totalGuests: 150,
      confirmed: 148,
      checkedIn: 142,
      pending: 2,
      declined: 0,
      vendorsCount: 8,
      budgetTotal: 180000,
      budgetSpent: 175000,
      planner: "Diego Morales",
      status: "COMPLETED",
      coverColor: "linear-gradient(135deg, #18181b 0%, #27272a 50%, #3f3f46 100%)",
      badge: "Finished"
    },
    {
      id: "evt-05",
      name: "Graduación Medicina TEC 2026",
      type: "Graduación & Gala",
      date: "18 JUL 2026",
      time: "8:30 PM",
      location: "Showcenter Complex",
      totalGuests: 600,
      confirmed: 580,
      checkedIn: 0,
      pending: 15,
      declined: 5,
      vendorsCount: 16,
      budgetTotal: 520000,
      budgetSpent: 410000,
      planner: "Sofia Garza",
      status: "UPCOMING",
      coverColor: "linear-gradient(135deg, #0c4a6e 0%, #0369a1 50%, #0284c7 100%)",
      badge: "Draft"
    }
  ],
  guests: [
    {
      id: "EV-002381",
      name: "Juan Pérez",
      group: "Familia Pérez",
      relationship: "Bride Family",
      status: "Confirmed",
      partySize: 4,
      table: "Mesa 18",
      seat: "B1 - B4",
      qrStatus: "Active",
      checkedIn: true,
      checkInTime: "7:45 PM",
      email: "juan.perez@email.com",
      phone: "+52 81 1234 5678",
      notes: "Vegetariano (2 invitados)",
      timeline: [
        { label: "Invitation Sent", date: "15 Jun 2026", completed: true },
        { label: "Invitation Opened", date: "16 Jun 2026", completed: true },
        { label: "RSVP Confirmed", date: "22 Jun 2026", completed: true },
        { label: "QR Generated", date: "22 Jun 2026", completed: true },
        { label: "Checked In (Puerta Principal)", date: "29 Aug 2026 · 7:45 PM", completed: true }
      ]
    },
    {
      id: "EV-002382",
      name: "Dra. Mariana Treviño",
      group: "Colegas Medicina",
      relationship: "Groom Friend",
      status: "Confirmed",
      partySize: 2,
      table: "Mesa 12",
      seat: "A1 - A2",
      qrStatus: "Active",
      checkedIn: false,
      checkInTime: null,
      email: "m.trevino@salud.org",
      phone: "+52 81 8765 4321",
      notes: "Alergia a mariscos",
      timeline: [
        { label: "Invitation Sent", date: "15 Jun 2026", completed: true },
        { label: "Invitation Opened", date: "17 Jun 2026", completed: true },
        { label: "RSVP Confirmed", date: "25 Jun 2026", completed: true },
        { label: "QR Generated", date: "25 Jun 2026", completed: true },
        { label: "Check-in Pending", date: "Esperado hoy", completed: false }
      ]
    },
    {
      id: "EV-002383",
      name: "Roberto Garza Sada",
      group: "Empresarios Monterrey",
      relationship: "VIP Sponsor",
      status: "Confirmed",
      partySize: 2,
      table: "Mesa 01 (VIP)",
      seat: "VIP-1",
      qrStatus: "Active",
      checkedIn: true,
      checkInTime: "7:20 PM",
      email: "rgarza@corporativo.com",
      phone: "+52 81 9988 7766",
      notes: "Atención protocolo",
      timeline: [
        { label: "Invitation Sent", date: "10 Jun 2026", completed: true },
        { label: "Invitation Opened", date: "10 Jun 2026", completed: true },
        { label: "RSVP Confirmed", date: "11 Jun 2026", completed: true },
        { label: "QR Generated", date: "11 Jun 2026", completed: true },
        { label: "Checked In (Acceso VIP)", date: "29 Aug 2026 · 7:20 PM", completed: true }
      ]
    },
    {
      id: "EV-002384",
      name: "Lucía Villarreal",
      group: "Amigas Novia",
      relationship: "Damas de Honor",
      status: "Confirmed",
      partySize: 1,
      table: "Mesa 05",
      seat: "C3",
      qrStatus: "Active",
      checkedIn: true,
      checkInTime: "6:50 PM",
      email: "lucia.v@agency.com",
      phone: "+52 81 3344 5566",
      notes: "",
      timeline: [
        { label: "Invitation Sent", date: "15 Jun 2026", completed: true },
        { label: "Invitation Opened", date: "15 Jun 2026", completed: true },
        { label: "RSVP Confirmed", date: "18 Jun 2026", completed: true },
        { label: "QR Generated", date: "18 Jun 2026", completed: true },
        { label: "Checked In (Staff/Damas)", date: "29 Aug 2026 · 6:50 PM", completed: true }
      ]
    },
    {
      id: "EV-002385",
      name: "Ing. Fernando Hinojosa",
      group: "Familia Hinojosa",
      relationship: "Groom Family",
      status: "Pending",
      partySize: 3,
      table: "Sin Asignar",
      seat: "-",
      qrStatus: "Inactive",
      checkedIn: false,
      checkInTime: null,
      email: "f.hinojosa@constructora.mx",
      phone: "+52 81 5566 7788",
      notes: "Recordatorio enviado por SMS",
      timeline: [
        { label: "Invitation Sent", date: "15 Jun 2026", completed: true },
        { label: "Invitation Opened", date: "20 Jun 2026", completed: true },
        { label: "RSVP Pending", date: "En espera", completed: false },
        { label: "QR Generation Pending", date: "-", completed: false },
        { label: "Check-in Pending", date: "-", completed: false }
      ]
    },
    {
      id: "EV-002386",
      name: "Camila Ortiz",
      group: "Ex-alumnos",
      relationship: "Friend",
      status: "Declined",
      partySize: 2,
      table: "N/A",
      seat: "N/A",
      qrStatus: "Cancelled",
      checkedIn: false,
      checkInTime: null,
      email: "cami.ortiz@design.io",
      phone: "+52 81 4455 6677",
      notes: "Fuera de la ciudad por viaje",
      timeline: [
        { label: "Invitation Sent", date: "15 Jun 2026", completed: true },
        { label: "Invitation Opened", date: "16 Jun 2026", completed: true },
        { label: "Declined", date: "19 Jun 2026", completed: true }
      ]
    }
  ],
  tables: [
    { id: "T-01", name: "Mesa 01 (VIP)", type: "Round", capacity: 8, assigned: 8, room: "Salón Imperial", zone: "VIP Front", guests: ["Roberto Garza Sada", "Sra. Garza", "Lic. Villarreal", "Esposa Villarreal", "Don Patricio", "Doña Elena", "Emilio Sada", "Mariana Sada"] },
    { id: "T-02", name: "Mesa 02", type: "Round", capacity: 10, assigned: 10, room: "Salón Imperial", zone: "Center Left", guests: ["Familia Morales (4)", "Familia Ramos (4)", "Sergio Garza (2)"] },
    { id: "T-03", name: "Mesa 03", type: "Round", capacity: 10, assigned: 9, room: "Salón Imperial", zone: "Center Right", guests: ["Grupo Arquitectura (6)", "Invitados Arcano (3)"] },
    { id: "T-04", name: "Mesa 04 (Familia Novio)", type: "Imperial", capacity: 14, assigned: 14, room: "Salón Imperial", zone: "Stage Front", guests: ["Papás Novio", "Hermanos (4)", "Tíos Directos (6)", "Abuelos (2)"] },
    { id: "T-05", name: "Mesa 05 (Damas)", type: "Round", capacity: 10, assigned: 10, room: "Salón Imperial", zone: "Dance Floor Left", guests: ["Lucía Villarreal", "Damas de Honor (8)", "Coordinadora"] },
    { id: "T-12", name: "Mesa 12 (Colegas)", type: "Round", capacity: 10, assigned: 8, room: "Salón Jardín", zone: "Garden Side", guests: ["Dra. Mariana Treviño (2)", "Dr. Lozano (2)", "Dra. Cantú (2)", "Dr. Garza (2)"] },
    { id: "T-18", name: "Mesa 18 (Familia Pérez)", type: "Round", capacity: 10, assigned: 10, room: "Salón A", zone: "Main Hall", guests: ["Juan Pérez (4)", "Familia Martínez Pérez (4)", "Tía Rosa (2)"] },
    { id: "T-19", name: "Mesa 19", type: "Round", capacity: 10, assigned: 7, room: "Salón A", zone: "Main Hall", guests: ["Amigos Universidad (7)"] },
    { id: "T-20", name: "Mesa 20 (Juvenil)", type: "Rectangle", capacity: 12, assigned: 12, room: "Lounge Bar", zone: "Bar Area", guests: ["Primos Jóvenes (12)"] },
    { id: "T-21", name: "Mesa 21 (Staff)", type: "Rectangle", capacity: 8, assigned: 6, room: "Salón B", zone: "Backstage", guests: ["Planner Team (4)", "Seguridad Líder (2)"] }
  ],
  vendors: [
    {
      id: "v-01",
      name: "Luz & Eventos Pro",
      category: "Lighting & FX",
      contact: "Carlos Rodríguez",
      phone: "+52 81 2233 4455",
      status: "Confirmed",
      arrival: "3:00 PM",
      setup: "3:30 PM",
      cost: 35000,
      paid: 20000,
      balance: 15000,
      notes: "Estructura robótica central y pirotecnia fría para primer baile."
    },
    {
      id: "v-02",
      name: "Gourmet Banquetes MX",
      category: "Catering",
      contact: "Chef Marcela Aguirre",
      phone: "+52 81 8899 0011",
      status: "Confirmed",
      arrival: "12:00 PM",
      setup: "1:00 PM",
      cost: 165000,
      paid: 165000,
      balance: 0,
      notes: "Menú de 4 tiempos. 14 opciones vegetarianas y 3 libres de marisco."
    },
    {
      id: "v-03",
      name: "Visual Memories Cinema",
      category: "Photography & Video",
      contact: "Esteban Cruz",
      phone: "+52 81 6677 8899",
      status: "Payment Due",
      arrival: "2:00 PM",
      setup: "2:30 PM",
      cost: 45000,
      paid: 25000,
      balance: 20000,
      notes: "Equipo de 3 cámaras, dron y fotocabina para recepción."
    },
    {
      id: "v-04",
      name: "DJ Maxima Audio",
      category: "DJ & Sound",
      contact: "Javier Cantú",
      phone: "+52 81 3322 1100",
      status: "Confirmed",
      arrival: "4:00 PM",
      setup: "4:30 PM",
      cost: 28000,
      paid: 28000,
      balance: 0,
      notes: "Sistema Line Array y microfonía Shure Axient para ceremonia."
    },
    {
      id: "v-05",
      name: "Atelier Floral Design",
      category: "Flowers & Decor",
      contact: "Renata Lozano",
      phone: "+52 81 9900 1122",
      status: "Pending",
      arrival: "11:00 AM",
      setup: "11:30 AM",
      cost: 52000,
      paid: 30000,
      balance: 22000,
      notes: "Arcos de hortensias blancas y centros de mesa altos para 35 mesas."
    }
  ],
  tasks: [
    { id: "tsk-01", title: "Confirmar conteo final con Banquetes", assignee: "Sofia Garza", dueDate: "20 Ago", priority: "HIGH", status: "IN PROGRESS", category: "Catering" },
    { id: "tsk-02", title: "Revisión de generador eléctrico en Hacienda", assignee: "Carlos R.", dueDate: "24 Ago", priority: "HIGH", status: "TODO", category: "Operación" },
    { id: "tsk-03", title: "Validar pruebas de sonido con DJ", assignee: "Javier Cantú", dueDate: "28 Ago", priority: "MEDIUM", status: "WAITING", category: "Audio" },
    { id: "tsk-04", title: "Impresión de gafetes y credenciales VIP", assignee: "Elena Ramos", dueDate: "18 Ago", priority: "LOW", status: "COMPLETED", category: "Accesos" },
    { id: "tsk-05", title: "Asignar mesas finales de invitados confirmados", assignee: "Sofia Garza", dueDate: "25 Ago", priority: "HIGH", status: "IN PROGRESS", category: "Seating" }
  ],
  timeline: [
    { time: "10:00 AM", title: "Venue Setup & Decoración", desc: "Montaje inicial de carpa y estructuras florales", status: "completed" },
    { time: "12:00 PM", title: "Catering Arrival", desc: "Recepción de camiones refrigerados y mise en place", status: "completed" },
    { time: "02:00 PM", title: "Photography & Bride Prep", desc: "First look y sesión en jardines principales", status: "completed" },
    { time: "04:00 PM", title: "DJ & Audio Soundcheck", desc: "Prueba de microfonía inalámbrica y luces robóticas", status: "completed" },
    { time: "06:30 PM", title: "Guest Arrival & Check-in", desc: "Apertura de accesos QR y cóctel de bienvenida", status: "current" },
    { time: "07:30 PM", title: "Ceremony", desc: "Inicio solemne en Capilla de San José", status: "upcoming" },
    { time: "08:30 PM", title: "Dinner Service", desc: "Servicio de 4 tiempos por Gourmet Banquetes", status: "upcoming" },
    { time: "10:00 PM", title: "First Dance & Party Open", desc: "Apertura de pista de baile y pirotecnia fría", status: "upcoming" }
  ],
  notifications: [
    { id: "not-01", type: "warning", title: "38 invitados sin confirmar", desc: "Faltan 4 días para el cierre de banquetes.", time: "Hace 15m" },
    { id: "not-02", type: "due", title: "Pago pendiente: Visual Memories", desc: "Balance de $20,000 MXN vence mañana.", time: "Hace 1h" },
    { id: "not-03", type: "success", title: "Check-in exitoso", desc: "Familia Pérez (4 personas) ingresó por Puerta 1.", time: "Hace 2h" },
    { id: "not-04", type: "info", title: "Mesa 18 al 100% de capacidad", desc: "Capacidad asignada completada (10/10).", time: "Hace 3h" }
  ]
};
